import { vectorEmbeddingFromAI } from "./Embeddings/vectorEmbeddingFromAI.js";
import { supabase } from "./config.js";

// Query Supabase and return a semantically matching text chunk
async function handleUserQuery(userQuery, matchTable) {
    try {

        // Create a vector embedding representing the input text
        const embeddingResponse = await vectorEmbeddingFromAI(userQuery)

        // The vector generated by OpenAI
        const embedding = embeddingResponse.data[0].embedding;

        // Query Supabase for nearest vector match
        const { data } = await supabase.rpc(matchTable, {
            query_embedding: embedding,
            match_threshold: 0.50,
            match_count: 4
        });

        // Manage multiple returned matches
        const match = data.map(chunk => chunk.content).join("\n")

        return match
    }
    catch (err) {
        console.error(err)
    }
}

export { handleUserQuery }